# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 312f4f97d5aea713e2fad14d68d348fca71762b54b77f32ca05d3fb5140872f645664fc28628046cb10d64ba279f089ca3a9fa43b1b4ce5264d5f891047c8dc1

test:
  secret_key_base: cb5f36c87c7dcd4080e9f25b0235bab587f972666f0ca29997cc57767de601269942e0c2742b97d9db04225a6e9c324b8d8fa56a8080095a291e2602da443093

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
